let NomeCharacter
let EnderecoCharacter
let NacionalidadeCharacter
let IdadeCharacter

NomeCharacter = prompt("Digite seu nomezinho: ")
EnderecoCharacter = prompt("Digite seu endereço: ")
NacionalidadeCharacter = prompt("Digite sua nacionalidade: ")
IdadeCharacter = prompt("Digite sua idade: ")

alert(`Cliente ${NomeCharacter} com ${IdadeCharacter} anos ${NacionalidadeCharacter} reside no endereço ${EnderecoCharacter}`)